### ISSUE TITLE
Upload form and multi-file bios

### ISSUE THREAD

**Issue by Ramaerel** [n-at/playtime#1]
Hi, I thought I'd check this out for inspiration- It's an incredible project and honestly; I could never hope to come close.

That said, I might be doing something wrong but I cannot find a way to upload games at all. I've tried every page, I haven't tried looking through the docker container and manually putting roms in- is there something I'm missing?

Also, I noticed that the NDS bios is a selection of the three bios files. The NDS bios typciallt doesn't function correctly unless all 3 are used, it might be a good idea to zip them and include them that way- same with any other multi-file bioses

**Comment by Ramaerel** [comment]
I figured out the upload thing- My bad. That said, a method to make it doable on mobile would be good, I couldn't find any

**Comment by n-at** [comment]
Hello. 
I've reorganized template forgot to show upload button if no games uploaded. Now it's fixed.

**Comment by n-at** [comment]
Collected bios files for DS and PC-FX into zip archives.
