### ISSUE TITLE
Install bombs out after let's encrypt keygen

### ISSUE THREAD

**Issue by RiffyDivine** [n-at/playtime#3]
Not sure if I just did something wrong or missed a step but after the let's encrypt phase I get this dumped out. I am not sure if it's cause it is now docker compose and not docker-compose or if I just messed up. During the setup I did point the IP to my servers external IP and a url I directed to that IP. 

```
./quick-install.sh: line 63: docker-compose: command not found
./quick-install.sh: line 67: docker-compose: command not found
no crontab for root
>>>>>>>>>> SETUP COTURN <<<<<<<<<<
./quick-install.sh: line 90: docker-compose: command not found
>>>>>>>>>> SETUP PLAYTIME <<<<<<<<<<
./quick-install.sh: line 101: docker-compose: command not found
./quick-install.sh: line 107: docker-compose: command not found
cat: playtime/data/admin.password: No such file or directory
>>>>>>>>>> DONE <<<<<<<<<<
```

**Comment by n-at** [comment]
I've tried to fix this in https://github.com/n-at/playtime/commit/1122a8b14289388b446f5f01ebb06bd4b0581224 Now it should support `docker compose` too.

**Comment by n-at** [comment]
I think TURN server needs a public/direct IP address.
