### ISSUE TITLE
Where is the ./app

### ISSUE THREAD

**Issue by RiffyDivine** [n-at/playtime#5]
I can't seem to find it where to run the commands to see where the turn server is aiming, the issue I am still having with netplay seems to be with the turn server and setting it up correctly.

**Comment by RiffyDivine** [comment]
Does it default to port 3478 and does it set any login information?

**Comment by n-at** [comment]
No, it will pass those values as is to clients. If user and password are not set or empty client will also not set them: https://github.com/n-at/playtime/blob/master/assets/netplay.js#L1184
