### ISSUE TITLE
Sony Playstation no virtual gamepad for netplay second player

### ISSUE THREAD

**Issue by vb87** [n-at/playtime#6]
Gamepad shows only for server (first player) - second player has no gamepad, input works though if using keyboard, toggling show virtual gamepad does nothing. This is for PS1, gamepad works for second player on NES. Didn't test others.

![image](https://github.com/user-attachments/assets/5678b450-33c6-4ac7-8048-456173c81037)

![Attachment-1](https://github.com/user-attachments/assets/ade495a1-5d13-4be2-b235-52da3546643f)

**Comment by n-at** [comment]
Host and netplay clients are using different libraries for virtual gamepad. Virtual gamepad for PS1 netplay client not yet implemented. Keyboard controls and physical gamepads should work.
